name: aEventos
version: ${project.version}
description: O seu plugin de eventos!

author: Ars3ne
website: ${project.url}

main: com.ars3ne.eventos.aEventos
softdepend: [LegendChat, SimpleClans, Vault]

commands:
  evento:
    description: Comando principal do plugin.